version: '3.8'

services:
  mooc-api:
    build: .
    environment:
      MOOC_HOST: 127.0.0.1
      MOOC_DBHOST: mysql
    ports:
      - 8081:8080

  mysql_2:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: go-api
      MYSQL_USER: go-api
      MYSQL_PASSWORD: go-api
      MYSQL_ROOT_PASSWORD: go-api
    ports:
      - 3308:3306
volumes:
  mysql_data: